language: python

python:
  - 2.7

env:
  - DJANGO_VERSION=1.8.13

addons:
  apt:
    packages:
      libxml2-dev
      libxslt-dev

sudo: false

branches:
  only:
    - master
    - django1.8

script:
  - coverage run --source=app manage.py test --settings=associados.settings_test --verbosity=2

install:
  - pip install -r requirements_test.txt
  - pip install coveralls --use-mirrors

after_success: coveralls
